/* DATA bridge: stable IDs connect existing list rows to existing drawing arrays. */
(function(global){
'use strict';
const clone=x=>JSON.parse(JSON.stringify(x));
const VERSION=1,KEY='chizu-user-data-v1',KINDS=[[2,'駅'],[1,'勾配'],[3,'トンネル'],[7,'曲線'],[8,'上り信号'],[9,'下り信号'],[10,'上り有電源'],[11,'下り有電源'],[12,'無電源'],[5,'進入路・避難口'],[6,'kp']];
const common=[['id','ID'],['currentOrder','元番号'],['distanceOrder','距番号'],['distanceKm','距離_km'],['y','表示Y'],['type1','種別']];
function schema(code){return common.concat(code===1?[['type2','勾配_‰']]:code===2?[['type2','駅名']]:code===3?[['type2','名称_元表記'],['type3','延長_m']]:code===7?[['type2','曲線記号'],['type3','R_m'],['direction','左右_1左_-1右'],['curveNote','曲線備考']]:[8,9,10,11].includes(code)?[['type2','区分'],['type3','名称'],...([10,11].includes(code)?[['controlDistance','制御距離_m']]:[])]:code===12?[['type2','分類'],['type3','補足値'],['drawCode','図の名称'],['value','設定値']]:[['type2','名称'],['type3','補足値']]);}
function createBridge(route,rows,profiles){
 const base={route:clone(route),rows:clone(rows),profiles:clone(profiles)},byId=new Map(base.rows.map(r=>[r.id,r])),links={},used=new Set();
 const enrich=new Map(base.rows.map(r=>[r.id,{id:r.id,currentOrder:r.currentOrder,distanceOrder:r.distanceOrder,distanceKm:r.distanceKm,y:r.y,type1:r.type1,type2:r.type2,type3:r.type3}]));
 function find(k,p,code){let candidates=base.rows.filter(r=>code.includes(Number(r.categoryCode))&&(!p.direction||k==='curves'||r.categoryName===p.direction)),matches=candidates.filter(r=>Math.abs(r.distanceKm-p.km)<1e-8);if(matches.length===1)return matches[0];if(k==='poweredBalises'){matches=candidates.filter(r=>r.type3===p.code&&Math.abs(r.distanceKm-p.km)<.2);if(matches.length===1)return matches[0];}throw Error('基準DATAの対応を確認できません：'+k+' '+p.km);}
 for(const [k,codes] of [['gradient',[1]],['stations',[2]],['exits',[5]],['curves',[7]],['signals',[8,9]],['poweredBalises',[10,11]],['passiveBalises',[12]]]){
  links[k]=base.route[k].map((p,i)=>{const r=find(k,p,codes),entry=enrich.get(r.id);if(used.has(r.id))throw Error('基準DATAの重複対応：'+r.id);used.add(r.id);if(k==='curves'){entry.direction=p.direction;entry.curveNote=p.note||'';}if(k==='poweredBalises')entry.controlDistance=p.distance??null;if(k==='passiveBalises'){entry.drawCode=p.code;entry.value=p.value??null;}return r.id;});
 }
 links.tunnels=base.route.tunnels.map(t=>{const pair=['T始点','T終点'].map((type,i)=>base.rows.filter(r=>r.type1===type&&Math.abs(r.distanceKm-(i?t.end:t.start))<1e-8));if(pair.some(a=>a.length!==1))throw Error('トンネル対応が不明：'+t.name);return pair.map(a=>a[0].id);});
 const initial={format:'chizu-data',version:VERSION,sourceVersion:'13.14A',entries:[...enrich.values()],points:base.route.points.map((p,i)=>({id:i+1,...clone(p)})),speeds:Object.fromEntries(Object.entries(base.profiles).map(([id,p])=>[id,p.points.map((r,i)=>({id:i+1,km:r.km,up:r.up,down:r.down}))]))};
 let active=null,loadWarning='';
 const requiredString=(v,max=160)=>typeof v==='string'&&v.trim().length>0&&v.length<=max&&!/[\x00-\x08\x0b\x0c\x0e-\x1f]/.test(v);
 const num=(v,min=-Infinity,max=Infinity)=>typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max;
 function validate(doc){const errors=[],warnings=[];function err(s){if(errors.length<120)errors.push(s);}if(doc?.format!=='chizu-data'||doc?.version!==VERSION)return {errors:['このアプリのDATA形式ではありません。'],warnings,counts:{}};
  if(!Array.isArray(doc.entries)||!Array.isArray(doc.points)||!doc.speeds)return {errors:['構造物・分岐器・速度DATAが不足しています。'],warnings,counts:{}};
  const entries=new Map(),initialMap=new Map(initial.entries.map(e=>[e.id,e]));
  if(doc.entries.length!==initial.entries.length)err('構造物の行数が違います。初版は既存'+initial.entries.length+'行の値の編集に対応しています。');
  for(const r of doc.entries){const b=initialMap.get(r?.id),old=byId.get(r?.id),where='ID '+r?.id+'：';if(!b){err(where+'存在しないID');continue;}if(entries.has(r.id)){err(where+'ID重複');continue;}entries.set(r.id,r);
   for(const key of ['currentOrder','distanceOrder','type1'])if(r[key]!==b[key])err(where+({currentOrder:'元番号',distanceOrder:'距番号',type1:'種別'}[key])+'は変更できません。');
   if(!num(r.distanceKm,-.1,56.2))err(where+'距離_kmは-0.1～56.2の数値で入力してください。');if(!num(r.y,-10,10))err(where+'表示Yが不正です。');
   const code=Number(old.categoryCode);if(![1,7].includes(code)&&!num(r.distanceKm,0,base.route.meta.totalKm))err(where+'この種類の距離は0～56.1kmで入力してください。');
   if(code===1){if(r.type2!==null&&!num(r.type2,-100,100))err(where+'勾配は-100～100‰の数値。終点の空欄はそのままにしてください。');if(r.y!==b.y)err(where+'勾配の表示Yは自動計算用です。変更せず勾配・距離を編集してください。');if((r.type2===null)!==(b.type2===null))err(where+'勾配終点の空欄は変更できません。');}
   else if(code===7){if(r.type2!==b.type2)err(where+'曲線記号は変更せず、距離・R・左右を編集してください。');if(r.type3!==null&&!num(r.type3,1,100000))err(where+'R_mは正の数値または空欄。');if(![1,-1].includes(r.direction))err(where+'左右は1（左）または-1（右）。');if(typeof r.curveNote!=='string'||r.curveNote.length>500)err(where+'曲線備考が不正です。');}
   else {if(r.type1==='T勾配'){if(r.type2!==b.type2)err(where+'トンネル内勾配の名称欄は変更しないでください。');}else if(!requiredString(r.type2))err(where+'名称・区分が空欄または長すぎます。');if(r.type3!==null&&typeof r.type3!=='string'&&!num(r.type3))err(where+'補足値が不正です。');if(typeof r.type3==='string'&&r.type3.length>160)err(where+'名称／補足値が長すぎます。');if([8,9,10,11].includes(code)&&!requiredString(r.type3))err(where+'信号・有電源地上子の名称が必要です。');}
   if(code===3&&r.type3!==null&&!num(r.type3,0,100000))err(where+'延長_mが不正です。');if([10,11].includes(code)&&r.controlDistance!==null&&!num(r.controlDistance,0,100000))err(where+'制御距離_mが不正です。');if(code===12){if(!requiredString(r.drawCode))err(where+'図の名称が必要です。');if(r.value!==null&&!num(r.value,0,100000))err(where+'設定値が不正です。');}
  }
  for(const b of initial.entries)if(!entries.has(b.id))err('ID '+b.id+'：行がありません。');
  for(const [i,ids] of links.tunnels.entries()){const s=entries.get(ids[0]),e=entries.get(ids[1]);if(!s||!e)continue;if(!(s.distanceKm<e.distanceKm))err('トンネル ID '+ids[0]+'：始点が終点より手前にある必要があります。');if(String(s.type2).replace(/^[12]/,'').normalize('NFKC')!==String(e.type2).replace(/^[12]/,'').normalize('NFKC'))err('トンネル ID '+ids.join('/')+'：始点・終点の名称をそろえてください。');if(!String(s.type2).startsWith('1')||!String(e.type2).startsWith('2'))err('トンネル名称_元表記は始点の1、終点の2を残してください。');const length=(e.distanceKm-s.distanceKm)*1000;if(s.type3!==null&&Math.abs(length-s.type3)>2)warnings.push('トンネル ID '+ids[0]+'：始終点間と延長_mに差があります。');if(s.type3!==e.type3)warnings.push('トンネル ID '+ids.join('/')+'：延長_mの記載が異なります。');}
  for(const key of ['gradient','stations','curves']){const sorted=links[key].map(id=>entries.get(id)).filter(Boolean).sort((a,b)=>a.distanceKm-b.distanceKm);for(let i=1;i<sorted.length;i++)if(sorted[i].distanceKm===sorted[i-1].distanceKm)err(key+'：距離が重複しています（ID '+sorted[i].id+'）。');}
  // Prevent reordered curve boundaries from silently producing another shape.
  const ordered=links.curves.map(id=>entries.get(id)).filter(Boolean).sort((a,b)=>a.distanceKm-b.distanceKm).map(e=>e.id);if(ordered.length===links.curves.length&&ordered.some((id,i)=>id!==links.curves[i]))err('曲線の境界の前後関係が逆転しています。距離を確認してください。');
  if(doc.points.length!==initial.points.length)err('分岐器の行数は'+initial.points.length+'行を維持してください。');const pointIds=new Set();for(const p of doc.points){if(!Number.isInteger(p?.id)||p.id<1||p.id>initial.points.length||pointIds.has(p.id))err('分岐器：IDが不正または重複しています。');pointIds.add(p.id);if(!requiredString(p.name)||!num(p.km,0,base.route.meta.totalKm)||!['上り','下り'].includes(p.direction))err('分岐器 ID '+p.id+'：名称・距離・方向を確認してください。');}
  if(Object.keys(doc.speeds).some(id=>!initial.speeds[id]))err('未対応の速度シートがあります。');
  for(const id of Object.keys(initial.speeds)){const rs=doc.speeds[id],bs=initial.speeds[id];if(!Array.isArray(rs)||rs.length!==bs.length){err('速度_'+id+'：'+bs.length+'行が必要です。');continue;}const ids=new Set();for(const r of rs){if(!Number.isInteger(r?.id)||r.id<1||r.id>bs.length||ids.has(r.id))err('速度_'+id+'：IDが不正または重複。');ids.add(r.id);if(!num(r.km,0,base.route.meta.totalKm)||!num(r.up,0,150)||!num(r.down,0,150))err('速度_'+id+' ID '+r.id+'：距離0～56.1km、速度0～150km/hの数値が必要です。');}const sorted=rs.slice().sort((a,b)=>a.km-b.km);for(let i=1;i<sorted.length;i++)if(sorted[i].km===sorted[i-1].km)err('速度_'+id+'：同じ距離が重複しています。');if(sorted[0].km>0||sorted.at(-1).km<base.route.meta.totalKm)err('速度_'+id+'：0km～56.1kmを含めてください。');}
  const counts=Object.fromEntries(KINDS.filter(([c])=>c!==6||base.rows.some(r=>Number(r.categoryCode)===c)).map(([c,n])=>[n,doc.entries.filter(e=>Number(byId.get(e.id)?.categoryCode)===c).length]));counts['トンネル区間']=base.route.tunnels.length;counts['分岐器']=doc.points.length;for(const id of Object.keys(initial.speeds))counts['速度_'+id]=doc.speeds[id]?.length||0;
  for(const [i,id] of links.poweredBalises.entries())if(Math.abs(base.route.poweredBalises[i].km-byId.get(id).distanceKm)>1e-8&&entries.get(id)?.distanceKm===byId.get(id).distanceKm)warnings.push('有電源 ID '+id+'：基準DATAの一覧距離と図距離の差を保持します。位置を編集すると両方に反映します。');
  return {errors,warnings:[...new Set(warnings)],counts};
 }
 function build(doc){const v=validate(doc);if(v.errors.length)throw Error(v.errors.join('\n'));const R=clone(base.route),P=clone(base.profiles),E=new Map(doc.entries.map(e=>[e.id,e]));
  const A=base.rows.map(old=>{const e=E.get(old.id),r={...clone(old),distanceKm:e.distanceKm,y:e.y,type2:e.type2,type3:e.type3};if(Number(r.categoryCode)===7){r.categoryName=e.type2;r.attribute=e.type3;}else if([8,9,10,11].includes(Number(r.categoryCode))){r.attribute=e.type2;r.supplementalB=e.type3;}else{if(Number(r.categoryCode)!==1)r.categoryName=e.type2;r.attribute=Number(r.categoryCode)===1?e.type2:e.type3;}r.raw=[r.currentOrder,r.distanceOrder,r.distanceKm,r.y,r.categoryCode,r.type1,r.type2,r.type3];return r;}).sort((a,b)=>a.distanceKm-b.distanceKm||a.distanceOrder-b.distanceOrder);
  for(const k of Object.keys(links).filter(k=>k!=='tunnels'))R[k]=base.route[k].map((p,i)=>{const id=links[k][i],e=E.get(id),old=byId.get(id),n=clone(p);if(e.distanceKm!==old.distanceKm)n.km=e.distanceKm;if(k!=='curves'&&e.y!==old.y)n.y=e.y;if(k==='gradient')n.permille=e.type2??0;if((k==='stations'||k==='exits')&&e.type2!==old.type2)n.name=e.type2;if(k==='signals'){if(e.type2!==old.type2)n.kind=e.type2;if(e.type3!==old.type3)n.code=e.type3;}if(k==='poweredBalises'){n.code=e.type3;n.distance=e.controlDistance;}if(k==='passiveBalises'){n.code=e.drawCode;n.value=e.value;}if(k==='curves'){n.mark=e.type2;n.direction=e.direction;n.note=e.curveNote;if(e.type3!==old.type3)n.radius=e.type3??(['BC','BTC','EIT'].includes(e.type2)?0:2);}return n;});
  for(const k of ['gradient','stations','exits','curves','signals','poweredBalises','passiveBalises'])if(links[k].some(id=>E.get(id).distanceKm!==byId.get(id).distanceKm))R[k].sort((a,b)=>a.km-b.km);
  if(links.gradient.some(id=>{const e=E.get(id),o=byId.get(id);return e.distanceKm!==o.distanceKm||e.type2!==o.type2;})){for(let i=1;i<R.gradient.length;i++){const a=R.gradient[i-1],b=R.gradient[i];b.y=Number((a.y+(b.km-a.km)*a.permille/1000).toFixed(9));}for(const r of A.filter(r=>Number(r.categoryCode)===1)){r.y=R.gradient.find(g=>g.km===r.distanceKm).y;r.raw[3]=r.y;}}
  R.tunnels=links.tunnels.map(([a,b],i)=>({...clone(base.route.tunnels[i]),start:E.get(a).distanceKm,end:E.get(b).distanceKm,name:E.get(a).type2===byId.get(a).type2?base.route.tunnels[i].name:String(E.get(a).type2).replace(/^1/,'')})).sort((a,b)=>a.start-b.start);
  R.points=doc.points.slice().sort((a,b)=>a.km-b.km).map(({id,...p})=>p);
  for(const [id,rs] of Object.entries(doc.speeds)){const old=base.profiles[id].points;P[id].points=rs.slice().sort((a,b)=>a.km-b.km).map(r=>({...clone(old[r.id-1]),km:r.km,...('m' in old[r.id-1]?{m:r.km===old[r.id-1].km?old[r.id-1].m:r.km*1000}:{}),up:r.up,down:r.down}));if(id==='7000')R.speeds=P[id].points;for(const stop of P[id].stops||[]){const idx=base.route.stations.findIndex(s=>Math.abs(s.km-stop.km)<.02);if(idx>=0){const e=E.get(links.stations[idx]),b=byId.get(e.id);if(e.distanceKm!==b.distanceKm)stop.km=e.distanceKm;if(e.type2!==b.type2)stop.name=e.type2;}}}
  return {route:R,rows:A,profiles:P};
 }
 function snapshot(liveProfiles=profiles){const d=clone(active||initial);for(const [id,p] of Object.entries(liveProfiles))d.speeds[id]=p.points.map((r,i)=>({id:(active?.speeds[id]?.slice().sort((a,b)=>a.km-b.km)[i]?.id)||i+1,km:r.km,up:r.up,down:r.down}));return d;}
 function install(doc){const built=build(doc);global.RAIL_DATA=built.route;global.ASSET_ROWS=built.rows;global.TRAIN_SPEED_DATA=Object.fromEntries(Object.entries(built.profiles).filter(([id])=>id!=='7000'));active=clone(doc);}
 function load(storage){try{const raw=storage.getItem(KEY);if(raw){const doc=JSON.parse(raw);install(doc);global.CHIZU_DATA_ID=doc.datasetId||'imported';}}catch(e){loadWarning='保存DATAを使えないため基準DATAで起動しました：'+e.message;global.CHIZU_DATA_ID='';}return loadWarning;}
 function persist(doc,storage){const check=validate(doc);if(check.errors.length)throw Error(check.errors.join('\n'));const next=clone(doc);next.datasetId='data-'+Date.now()+'-'+Math.random().toString(36).slice(2,8);next.savedAt=new Date().toISOString();storage.setItem(KEY,JSON.stringify(next));return next;}
 function restore(storage){storage.removeItem(KEY);}
 function tables(doc=snapshot()){
  const metadata=[['項目','値'],['形式','chizu-data'],['形式版',VERSION],['アプリ版','13.15A'],['基準DATA','13.13A + 13.14A画面修正'],['現在DATA',active?'ユーザーDATA':'基準DATA'],['書出し日時',new Date().toISOString()],['編集方法','ID・元番号・距番号・種別は変更不可。並べ替え可。既存行の値のみ編集。距離はkm、速度はkm/h。'],['読込方法','全シートを残してxlsx形式で保存。数式ではなく値を入力。読込→検査→このDATAを使用。'],['トンネル','名称_元表記の先頭1（始点）／2（終点）を残し、両端の名称をそろえる。'],['勾配','勾配の表示Yは参照用。勾配と距離を編集すると高さを再計算。'],['曲線','左右：1=左、-1=右。R空欄の境界記号は元資料どおり。曲線記号は変更せず、境界の前後関係も維持。'],['位置差','有電源ID726・636・637は基準DATAに一覧と図の距離差あり。未編集なら保持、位置編集時は図も更新。'],['速度','画面に反映中の速度修整も出力。Excel適用後の微調整とJSONバックアップはDATA別に保持。'],['分類','無電源の略号の意味・動作は推測しない。'],['CSV','確認・非常用の一括書出し。CSV読込は初版では非対応。']];
  const all=[{name:'基本情報',rows:metadata}];for(const [code,name] of KINDS){const sc=schema(code),rs=doc.entries.filter(r=>Number(byId.get(r.id)?.categoryCode)===code);if(!rs.length)continue;all.push({name,rows:[sc.map(x=>x[1]),...rs.map(r=>sc.map(([k])=>r[k]??null))]});}
  all.push({name:'分岐器',rows:[['ID','名称','距離_km','方向'],...doc.points.map(p=>[p.id,p.name,p.km,p.direction])]});for(const [id,rs] of Object.entries(doc.speeds))all.push({name:'速度_'+id,rows:[['ID','距離_km','上り_kmh','下り_kmh'],...rs.map(r=>[r.id,r.km,r.up,r.down])]});return all;
 }
 function fromTables(sheets){const errors=[],result=clone(initial),allEntries=[];const dict=new Map(sheets.map(s=>[s.name,s.rows]));const meta=dict.get('基本情報');if(!meta||!meta.some(r=>r[0]==='形式'&&r[1]==='chizu-data')||!meta.some(r=>r[0]==='形式版'&&r[1]===VERSION))throw Error('このアプリから書き出したExcelではありません。');
  function read(name,fields){const rs=dict.get(name);if(!rs)throw Error('シート「'+name+'」がありません。');const headers=rs[0]||[],cols=fields.map(f=>headers.indexOf(f[1]));if(new Set(headers).size!==headers.length||cols.some(i=>i<0))throw Error(name+'：列名が不足または重複しています。');return rs.slice(1).filter(r=>r.some(v=>v!==null&&v!==undefined&&v!=='')).map((r,i)=>Object.fromEntries(fields.map(([k,h],j)=>[k,r[cols[j]]??null])));}
  for(const [code,name] of KINDS){if(!base.rows.some(r=>Number(r.categoryCode)===code))continue;const rs=read(name,schema(code));for(const r of rs)if(Number(byId.get(r.id)?.categoryCode)!==code)errors.push(name+'：ID '+r.id+'が別の種別または不明です。');allEntries.push(...rs.map(r=>({...clone(initial.entries.find(e=>e.id===r.id)||{}),...r}))); }
  result.entries=allEntries;result.points=read('分岐器',[['id','ID'],['name','名称'],['km','距離_km'],['direction','方向']]);for(const id of Object.keys(initial.speeds))result.speeds[id]=read('速度_'+id,[['id','ID'],['km','距離_km'],['up','上り_kmh'],['down','下り_kmh']]);
  // Preserve intentionally empty note strings in the data model.
  for(const e of result.entries)if(Number(byId.get(e.id)?.categoryCode)===7&&e.curveNote===null)e.curveNote='';
  // Excel keeps about 15 significant digits; restore insignificant binary tails.
  const entryBase=new Map(initial.entries.map(e=>[e.id,e]));
  for(const r of result.entries){const b=entryBase.get(r.id);if(b)for(const k of Object.keys(r))if(typeof r[k]==='number'&&typeof b[k]==='number'&&Math.abs(r[k]-b[k])<1e-10)r[k]=b[k];}
  for(const [id,rs] of Object.entries(result.speeds))for(const r of rs){const b=initial.speeds[id]?.find(e=>e.id===r.id);if(b)for(const k of ['km','up','down'])if(typeof r[k]==='number'&&Math.abs(r[k]-b[k])<1e-10)r[k]=b[k];}
  const check=validate(result);check.errors.unshift(...errors);return {doc:result,...check};
 }
 function stationByOriginalName(name){const i=base.route.stations.findIndex(s=>s.name===name);if(i<0)return null;const e=(active||initial).entries.find(e=>e.id===links.stations[i]);return global.RAIL_DATA.stations.find(s=>Math.abs(s.km-e.distanceKm)<1e-8)||null;}
 return {base,initial,links,validate,build,snapshot,load,persist,restore,tables,fromTables,stationByOriginalName,get active(){return active;},get warning(){return loadWarning;}};
}
global.createChizuDataBridge=createBridge;
if(global.RAIL_DATA&&global.ASSET_ROWS){try{global.CHIZU_DATA=createBridge(global.RAIL_DATA,global.ASSET_ROWS,{'7000':{id:'7000',label:'7000',kind:'express',source:'route-data.js',points:global.RAIL_DATA.speeds},...global.TRAIN_SPEED_DATA});global.CHIZU_DATA.load(global.localStorage);}catch(e){global.CHIZU_DATA_ERROR='DATA管理を準備できません：'+e.message;}}
})(typeof window==='undefined'?globalThis:window);
