(function(){'use strict';
const $=s=>document.querySelector(s),bridge=window.CHIZU_DATA;let candidate=null,busy=false,sequence=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const panel=document.createElement('section');panel.id='dataManager';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-labelledby','dataTitle');
panel.innerHTML=`<div class="data-card"><header><h2 id="dataTitle">DATA管理</h2><button id="dataClose" type="button">閉じる</button></header><p id="dataCurrent"></p><div class="data-actions"><button id="dataExcelExport" type="button">Excel書出し</button><button id="dataExcelImport" type="button">Excel読込</button><button id="dataCsvExport" type="button">CSV書出し</button><input id="dataFile" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" hidden></div><p>PCのExcelで編集し、xlsx形式で保存してください。既存行の値の編集と並べ替えに対応します。行の追加・削除、ID・元番号・距番号・種別の変更、数式は初版では読み込めません。</p><p>距離はkm、速度はkm/h。トンネルは始点・終点を別行にしている元の構成を維持しています。列の詳しい説明はExcelの「基本情報」にあります。</p><p id="dataStatus" role="status" aria-live="polite"></p><div id="dataResults"></div><div class="data-apply"><button id="dataApply" type="button" disabled>このDATAを使用</button><span>検査に通ったDATAだけ端末へ保存し、画面を再読込します。</span></div><hr><div class="data-restore"><button id="dataRestore" type="button">基準DATAに戻す</button><span>読込DATAを解除します。速度の微調整とJSONバックアップはDATA別に保持されます。基準DATAに戻すと、以前の基準DATA上の微調整も戻ります。</span></div><p class="data-note">書出しは、現在使っているDATAと修整後の速度を含みます。CSVは確認用の一括書出しです。Excel処理は端末内で行い、通信しません。</p></div>`;
document.body.append(panel);
const open=document.createElement('button');open.id='dataManageBtn';open.type='button';open.className='settings-list-button';open.textContent='DATA管理（Excel / CSV）';$('#layerSettings').parentElement.append(open);
const home=document.createElement('button');home.id='homeDataBtn';home.type='button';home.className='home-data';home.innerHTML='<strong>DATA管理</strong><span>Excel書出し・読込／CSV書出し</span>';$('.launch-choices').append(home);
let previous=null;
function setStatus(s){$('#dataStatus').textContent=s;}
function setBusy(on){busy=on;for(const id of ['dataExcelExport','dataExcelImport','dataCsvExport','dataRestore'])$('#'+id).disabled=on||!bridge;$('#dataApply').disabled=on||!candidate;}
function show(){previous=document.activeElement;window.CHIZU_APP_DATA_API?.prepare();panel.hidden=false;$('#dataCurrent').textContent=bridge?(bridge.active?'使用中：ユーザーDATA（'+(bridge.active.savedAt||'保存日時不明')+'）':'使用中：アプリ内の基準DATA（速度の微調整は別途適用）'):window.CHIZU_DATA_ERROR||'DATA管理を使えません。';setStatus(bridge?.warning||'Excelを読込すると、検査結果をここに表示します。');setBusy(false);$('#dataClose').focus();}
function close(){sequence++;candidate=null;$('#dataApply').disabled=true;panel.hidden=true;previous?.focus?.();}
open.onclick=home.onclick=show;$('#dataClose').onclick=close;
function download(bytes,name,type){const url=URL.createObjectURL(new Blob([bytes],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function filename(ext){return '智頭線_DATA_'+new Date().toISOString().slice(0,19).replace(/[:T]/g,'-')+'.'+ext;}
function currentTables(){window.CHIZU_APP_DATA_API?.prepare();return bridge.tables(bridge.snapshot(window.CHIZU_APP_DATA_API.getProfiles()));}
$('#dataExcelExport').onclick=async()=>{if(busy||!bridge)return;setBusy(true);setStatus('Excelを作成しています…');try{const bytes=await window.ChizuXlsx.write(currentTables());download(bytes,filename('xlsx'),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');setStatus('Excelを書き出しました。編集後は「Excel読込」で検査してください。');}catch(e){setStatus('書出しできません：'+e.message);}finally{setBusy(false);}};
$('#dataCsvExport').onclick=()=>{if(busy||!bridge)return;try{const tables=currentTables(),headers=['シート',...new Set(tables.flatMap(s=>s.rows[0]))],csv=[headers];for(const sheet of tables)for(const row of sheet.rows.slice(1)){const values=Array(headers.length).fill('');values[0]=sheet.name;sheet.rows[0].forEach((h,i)=>{values[headers.indexOf(h)]=row[i]??'';});csv.push(values);}const cell=v=>{const text=String(v??'');return '"'+(typeof v==='string'&&/^[=+\-@]/.test(text)?"'"+text:text).replace(/"/g,'""')+'"';};download('\ufeff'+csv.map(r=>r.map(cell).join(',')).join('\r\n'),filename('csv'),'text/csv;charset=utf-8');setStatus('CSVを書き出しました（確認用・読込非対応）。');}catch(e){setStatus('CSVを書き出せません：'+e.message);}};
$('#dataExcelImport').onclick=()=>{if(busy||!bridge)return;$('#dataFile').value='';$('#dataFile').click();};
$('#dataFile').onchange=async()=>{const file=$('#dataFile').files[0];if(!file||!bridge)return;candidate=null;const ticket=++sequence;$('#dataResults').innerHTML='';setBusy(true);setStatus(file.name+' を検査しています…');try{if(!/\.xlsx$/i.test(file.name))throw Error('xlsx形式のファイルを選択してください。');if(file.size>15*1024*1024)throw Error('15MB以下のExcelを選択してください。');const result=bridge.fromTables(await window.ChizuXlsx.read(await file.arrayBuffer()));if(ticket!==sequence)return;$('#dataResults').innerHTML='<table><thead><tr><th>DATA</th><th>件数</th></tr></thead><tbody>'+Object.entries(result.counts).map(([k,n])=>'<tr><td>'+esc(k)+'</td><td>'+n+'</td></tr>').join('')+'</tbody></table>'+renderMessages('エラー',result.errors)+renderMessages('警告',result.warnings);if(result.errors.length){setStatus('エラー '+result.errors.length+'件。修正して再読込してください。現在のDATAは変更していません。');}else{candidate=result.doc;setStatus('検査完了：エラー0件、警告'+result.warnings.length+'件。「このDATAを使用」で適用します。');}}catch(e){if(ticket!==sequence)return;setStatus('読込できません：'+e.message+' 現在のDATAは変更していません。');}finally{if(ticket===sequence)setBusy(false);}};
function renderMessages(title,list){return '<div class="data-messages '+(title==='エラー'?'error':'warning')+'"><strong>'+title+' '+list.length+'件</strong>'+(list.length?'<ul>'+list.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ul>':'')+'</div>';}
$('#dataApply').onclick=()=>{if(!candidate||busy)return;try{bridge.persist(candidate,localStorage);candidate=null;setBusy(true);setStatus('端末へ保存しました。新しいDATAで再読込します。');location.reload();}catch(e){setStatus('保存できません：'+e.message+' 現在のDATAは変更していません。');setBusy(false);}};
$('#dataRestore').onclick=()=>{if(busy||!bridge)return;try{bridge.restore(localStorage);setBusy(true);setStatus('基準DATAで再読込します。');location.reload();}catch(e){setStatus('基準DATAへ戻せません：'+e.message);setBusy(false);}};
panel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const focus=[...panel.querySelectorAll('button:not(:disabled),input:not([hidden])')],first=focus[0],last=focus.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
if(bridge?.warning||window.CHIZU_DATA_ERROR)$('#launchStatus').textContent=bridge?.warning||window.CHIZU_DATA_ERROR;
})();
