/* Generated by build-pwa.py. Do not edit version or hashes by hand. */
const RELEASE={"version":"13.21A-F","build":"b0cec0337b75ef9fbd86","files":{"app.js":"05b9d17f3dd2e32c619ed1c90111a14b9fa356e5eea471a2e763ba9959c72458","asset-data.js":"adcf5e932d3c5ad7b232763e1a6a0342a68c965350a855065dc93c3c5d3ea9fd","auto-scroll.js":"6716ab6f35bceba9f52b3b1f3abeaf359e8f226711006d4f47ddf9286f5878e4","data-core.js":"3a7801e2b92ce7213f2f597c2a7b999f6ede229562317c335b704dd332be876c","data-manager.js":"ac2b57f9e13330515089017f93e8504eb345239271f90c2aca493fee88beb417","fullscreen-ui.js":"84b5044cc05ce28a5e5efabf19c89c0a2138fb0067d3eba923ad402384492f3f","icon.svg":"33b9c21005f7b2b70c45d5042bd96a632259c8f0a7b42122fcc2dd2f73fc4b18","index.html":"ba0bb4eff0fda186b004268d934d3f549344beb9d50347e2c7ecd0a4cfbbcbf6","jszip.min.js":"acc7e41455a80765b5fd9c7ee1b8078a6d160bbbca455aeae854de65c947d59e","list-print.css":"b5d06071a5fa63a06878816b47091bebcd4eda2e35c082b7db4a34b6a29751f5","list-print.js":"20b4bc8e9fff130475b7e0da7d6d1f9f2f13d7d5b78c1b59d70f7e236ebbbfbd","manifest.webmanifest":"2157856e5a8cf34f0a5b9f24000be1c0d2b9621dc6156a86677879b0cb6b5090","pan-motion.js":"138663613e1c3e0aa3da1da8e5b091e8bd95db754f80b265b22ec766515074c3","pwa-update.js":"d600dacd2dfa189339caf48ff47c70b35c1ccb5b8f0ed7c7bb86be12aadbaf16","route-data.js":"e05c9e4a0539c46652a29c53e63af12d8450e67b58b479dec70feef241a4b318","speed-data.js":"991ef770f95b5d8c3ef7ec2718b7d9f8e9b78bea8e596f4dbf6badb45d62a3f9","speed-editor.js":"1358c09925a873b7405740831b76af251888fb1f9b837a4753b7101f9c6be485","styles.css":"e0f29533690595cf97219c2ca3e57f0a53fb28ff61795203baaf875ef0d4bef0","view-modes.js":"38357cbbbe139e3f91f436335d096212580c0de20499a97a3b60a56f2b24d965","xlsx-bridge.js":"fa36b6e25af225f5bf85d50368adcec28a0e59d8dc33b4516793d991861a0b45"}};
const CACHE='chizu-offline:'+encodeURIComponent(self.registration.scope)+':'+RELEASE.build;
const url=name=>new URL(name,self.registration.scope).href;
const READY=url('__offline_ready__');
const hex=bytes=>Array.from(new Uint8Array(bytes),n=>n.toString(16).padStart(2,'0')).join('');
async function ready(){const cache=await caches.open(CACHE);const marker=await cache.match(READY);if(!marker)throw Error('incomplete cache');for(const name of Object.keys(RELEASE.files)){if(!await cache.match(url(name)))throw Error('missing '+name);}return cache;}
self.addEventListener('install',event=>event.waitUntil((async()=>{
  const cache=await caches.open(CACHE);
  // Only this new, incomplete candidate can be removed; never the active release.
  const wasReady=!!await cache.match(READY);
  try{
    for(const [name,hash] of Object.entries(RELEASE.files)){
      const response=await fetch(url(name),{cache:'no-store',redirect:'error'});
      if(!response.ok)throw Error('HTTP '+response.status+' '+name);
      if(hex(await crypto.subtle.digest('SHA-256',await response.clone().arrayBuffer()))!==hash)throw Error('File mismatch: '+name);
      await cache.put(url(name),response);
    }
    await cache.put(READY,new Response(JSON.stringify({version:RELEASE.version,build:RELEASE.build})));
  }catch(error){if(!wasReady)await caches.delete(CACHE);throw error;}
  // Upgrades wait. Activation is requested only by the HOME button.
})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{await ready();await self.clients.claim();})()));
self.addEventListener('message',event=>{
  if(!['STATUS','ACTIVATE'].includes(event.data?.type))return;
  event.waitUntil((async()=>{try{await ready();event.ports[0]?.postMessage({ok:true,version:RELEASE.version,build:RELEASE.build});if(event.data.type==='ACTIVATE')await self.skipWaiting();}catch(error){event.ports[0]?.postMessage({ok:false,error:error.message});}})());
});
self.addEventListener('fetch',event=>{
  const request=event.request,u=new URL(request.url);
  if(request.method!=='GET'||u.origin!==self.location.origin||!u.href.startsWith(self.registration.scope))return;
  // Explicit update must consult the network, not an earlier release's cache.
  if(u.pathname===new URL('release.json',self.registration.scope).pathname){event.respondWith(fetch(request,{cache:'no-store'}));return;}
  const relative=u.pathname.slice(new URL(self.registration.scope).pathname.length);
  let name=relative;
  if(request.mode==='navigate'&&(relative===''||relative==='index.html'))name='index.html';
  if(!Object.prototype.hasOwnProperty.call(RELEASE.files,name))return;
  event.respondWith((async()=>{
    const cache=await caches.open(CACHE),hit=await cache.match(url(name));
    if(hit)return hit;
    // Recover an evicted individual file only if it still matches this exact release.
    try{const response=await fetch(url(name),{cache:'no-store'});if(!response.ok||hex(await crypto.subtle.digest('SHA-256',await response.clone().arrayBuffer()))!==RELEASE.files[name])throw Error('mismatch');await cache.put(url(name),response.clone());return response;}
    catch(_){return new Response('オフライン用ファイルを取得できません。オンラインで更新してください。',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}});}
  })());
});
