/* Narrow OOXML bridge for the app's values-only editing workbook. ZIP is local JSZip. */
(function(global){'use strict';
 const XML='http://schemas.openxmlformats.org/spreadsheetml/2006/main',REL='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
 const col=i=>{let n=i+1,s='';while(n){s=String.fromCharCode(65+(n-1)%26)+s;n=Math.floor((n-1)/26);}return s;};
 const idx=s=>[...s].reduce((n,c)=>n*26+c.charCodeAt(0)-64,0)-1;
 const root=s=>'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'+s;
 async function write(tables){if(!global.JSZip)throw Error('Excel処理ライブラリがありません。');const zip=new global.JSZip();
 zip.file('[Content_Types].xml',root('<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'+tables.map((s,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')+'</Types>'));
 zip.file('_rels/.rels',root('<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="'+REL+'/officeDocument" Target="xl/workbook.xml"/></Relationships>'));
 zip.file('xl/workbook.xml',root(`<workbook xmlns="${XML}" xmlns:r="${REL}"><bookViews><workbookView/></bookViews><sheets>${tables.map((s,i)=>`<sheet name="${esc(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets><calcPr calcId="191029" fullCalcOnLoad="1"/></workbook>`));
 zip.file('xl/_rels/workbook.xml.rels',root('<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+tables.map((s,i)=>`<Relationship Id="rId${i+1}" Type="${REL}/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')+`<Relationship Id="rId${tables.length+1}" Type="${REL}/styles" Target="styles.xml"/></Relationships>`));
 zip.file('xl/styles.xml',root(`<styleSheet xmlns="${XML}"><numFmts count="1"><numFmt numFmtId="164" formatCode="0.000000"/></numFmts><fonts count="2"><font><sz val="11"/><name val="Yu Gothic"/></font><font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Yu Gothic"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF173B4C"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`));
 tables.forEach((sheet,i)=>{const headers=sheet.rows[0],last=col(headers.length-1)+sheet.rows.length;const columns=headers.map((h,j)=>{const width=sheet.name==='基本情報'?(j?105:22):/ID|元番号|距番号/.test(h)?9:/名称|駅名|備考/.test(h)?26:/種別|分類|方向|区分|記号/.test(h)?17:18;return `<col min="${j+1}" max="${j+1}" width="${width}" customWidth="1"/>`;}).join('');const rows=sheet.rows.map((r,n)=>`<row r="${n+1}" ht="${n?22:32}" customHeight="1">${r.map((value,j)=>{if(value===null||value===undefined||value==='')return '';const style=n===0?1:/距離_km|表示Y/.test(headers[j])&&typeof value==='number'?2:0;const ref=col(j)+(n+1);return typeof value==='number'?`<c r="${ref}" s="${style}"><v>${value}</v></c>`:`<c r="${ref}" s="${style}" t="inlineStr"><is><t xml:space="preserve">${esc(value)}</t></is></c>`;}).join('')}</row>`).join('');zip.file(`xl/worksheets/sheet${i+1}.xml`,root(`<worksheet xmlns="${XML}"><dimension ref="A1:${last}"/><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/><selection pane="bottomLeft" activeCell="A2" sqref="A2"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="22"/><cols>${columns}</cols><sheetData>${rows}</sheetData>${sheet.name==='基本情報'?'':`<autoFilter ref="A1:${last}"/>`}<printOptions horizontalCentered="1"/><pageMargins left="0.25" right="0.25" top="0.3" bottom="0.3" header="0.15" footer="0.15"/><pageSetup paperSize="9" orientation="landscape" fitToWidth="1" fitToHeight="0"/></worksheet>`));});
 return zip.generateAsync({type:'uint8array',compression:'DEFLATE',compressionOptions:{level:6}});
 }
 const nodes=(n,tag)=>Array.from(n.getElementsByTagNameNS('*',tag));
 function parse(xml,path){if(/<!DOCTYPE/i.test(xml))throw Error(path+'：XML形式が不正です。');const d=new global.DOMParser().parseFromString(xml,'application/xml');if(nodes(d,'parsererror').length)throw Error(path+'：XMLを読み取れません。');return d;}
 async function read(bytes){if(bytes.byteLength>15*1024*1024)throw Error('Excelは15MB以下で読み込んでください。');const zip=await global.JSZip.loadAsync(bytes);if(Object.keys(zip.files).length>1500)throw Error('Excel内のファイル数が多すぎます。');const size=Object.values(zip.files).reduce((s,f)=>s+(f._data?.uncompressedSize||0),0);if(size>35*1024*1024)throw Error('Excel内のデータ量が多すぎます。');
 async function xml(path){const f=zip.file(path);if(!f)throw Error('Excel内に'+path+'がありません。');const text=await f.async('string');if(text.length>6*1024*1024)throw Error(path+'が大きすぎます。');return parse(text,path);}
 function resolve(base,target){if(!target||/^[a-z]+:/i.test(target))throw Error('外部参照は読み込めません。');const parts=(target.startsWith('/')?target.slice(1):base+target).split('/'),out=[];for(const p of parts){if(p==='..')out.pop();else if(p&&p!=='.')out.push(p);}return out.join('/');}
 const book=await xml('xl/workbook.xml'),relationships=nodes(await xml('xl/_rels/workbook.xml.rels'),'Relationship'),rel=new Map(relationships.map(r=>[r.getAttribute('Id'),r]));let strings=[];const ss=relationships.find(r=>r.getAttribute('Type').endsWith('/sharedStrings'));if(ss){strings=nodes(await xml(resolve('xl/',ss.getAttribute('Target'))),'si').map(si=>nodes(si,'t').map(n=>n.textContent).join(''));}
 const sheets=nodes(book,'sheet');if(sheets.length>30)throw Error('シート数が多すぎます。');const names=new Set(),tables=[];
 for(const sheet of sheets){const name=sheet.getAttribute('name'),rid=sheet.getAttributeNS(REL,'id')||sheet.getAttribute('r:id'),r=rel.get(rid);if(!r||r.getAttribute('TargetMode')==='External')throw Error(name+'：シート参照が不正です。');if(names.has(name))throw Error('シート名が重複しています。');names.add(name);const doc=await xml(resolve('xl/',r.getAttribute('Target'))),out=[],seen=new Set();
 for(const row of nodes(doc,'row')){const n=Number(row.getAttribute('r'));if(!Number.isInteger(n)||n<1||n>10000)throw Error(name+'：行番号が不正です。');if(out[n-1])throw Error(name+'：行番号が重複しています。');const values=[];for(const cell of nodes(row,'c')){const address=cell.getAttribute('r'),m=/^([A-Z]+)([0-9]+)$/.exec(address||'');if(!m||Number(m[2])!==n||idx(m[1])>99||seen.has(address))throw Error(name+'：セル番地が不正です。');seen.add(address);if(nodes(cell,'f').length)throw Error(name+'!'+address+'：数式が入っています。Excelで値に変換してから読み込んでください。');const t=cell.getAttribute('t'),v=nodes(cell,'v')[0]?.textContent;let value=null;if(t==='s'){const k=Number(v);if(!Number.isInteger(k)||k<0||k>=strings.length)throw Error(name+'!'+address+'：文字列参照が不正です。');value=strings[k];}else if(t==='inlineStr')value=nodes(cell,'t').map(n=>n.textContent).join('');else if(t==='str')value=v??null;else if(t==='e')throw Error(name+'!'+address+'：Excelのエラー値があります。');else if(v!==undefined&&v!==''){value=Number(v);if(!Number.isFinite(value))throw Error(name+'!'+address+'：数値を読み取れません。');if(t==='b')value=Boolean(value);}values[idx(m[1])]=value;}out[n-1]=values;}
 tables.push({name,rows:Array.from({length:out.length},(_,i)=>out[i]||[])});
 }
 return tables;
 }
 global.ChizuXlsx={write,read,col};
})(typeof window==='undefined'?globalThis:window);
